//
// Created by Josue Flores on 12/04/2026.
//

#ifndef TAREA_VIII_LISTA_DOBLEMENTE_ENLAZADA_PROGRAMA_MEJORADO_H
#define TAREA_VIII_LISTA_DOBLEMENTE_ENLAZADA_PROGRAMA_MEJORADO_H


class Programa_mejorado
{
};


#endif //TAREA_VIII_LISTA_DOBLEMENTE_ENLAZADA_PROGRAMA_MEJORADO_H